server:
  port: 8080
  error.include-stacktrace: never

spring:
  application.name: order-item-service
  h2.console.enabled: true
  jpa.show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb